services:
  mysql:
    image: mysql:8.0
    container_name: food_search_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: food_db
      MYSQL_USER: food_user
      MYSQL_PASSWORD: food_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
